"""refactor ticket system

Revision ID: 9a3e80973ae9
Revises: 4972b1566e28
Create Date: 2026-02-02 21:12:47.161244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a3e80973ae9'
down_revision: Union[str, Sequence[str], None] = '4972b1566e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('check_in_deadline', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'MISSED', name='checkinstatus'), nullable=False),
    sa.Column('method', sa.Enum('SELF', 'VOLUNTEER', 'SYSTEM', name='checkinmethod'), nullable=False),
    sa.ForeignKeyConstraint(['senior_id'], ['senior_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('senior_volunteers')
    op.add_column('senior_profiles', sa.Column('assigned_volunteer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'senior_profiles', 'users', ['assigned_volunteer_id'], ['id'])
    op.drop_column('senior_profiles', 'phone_number')
    op.drop_column('senior_profiles', 'check_in_deadline')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('senior_profiles', sa.Column('check_in_deadline', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('senior_profiles', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'senior_profiles', type_='foreignkey')
    op.drop_column('senior_profiles', 'assigned_volunteer_id')
    op.create_table('senior_volunteers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('senior_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('volunteer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['senior_id'], ['senior_profiles.id'], name=op.f('senior_volunteers_senior_id_fkey')),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], name=op.f('senior_volunteers_volunteer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('senior_volunteers_pkey'))
    )
    op.drop_table('checkins')
    # ### end Alembic commands ###
