"""update checkin model

Revision ID: e85cacb6fae2
Revises: 9a3e80973ae9
Create Date: 2026-02-14 11:10:33.565960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e85cacb6fae2'
down_revision: Union[str, Sequence[str], None] = '9a3e80973ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('checkins_senior_id_fkey'), 'checkins', type_='foreignkey')
    op.drop_column('checkins', 'check_in_deadline')
    op.drop_column('checkins', 'status')
    op.drop_column('checkins', 'method')
    op.drop_column('checkins', 'senior_id')
    op.drop_column('checkins', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('checkins', sa.Column('senior_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('checkins', sa.Column('method', postgresql.ENUM('SELF', 'VOLUNTEER', 'SYSTEM', name='checkinmethod'), autoincrement=False, nullable=False))
    op.add_column('checkins', sa.Column('status', postgresql.ENUM('PENDING', 'COMPLETED', 'MISSED', name='checkinstatus'), autoincrement=False, nullable=False))
    op.add_column('checkins', sa.Column('check_in_deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('checkins_senior_id_fkey'), 'checkins', 'senior_profiles', ['senior_id'], ['id'])
    # ### end Alembic commands ###
